apiVersion: v2
appVersion: "1.0.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.0.1
deprecated: false
description: Dedicated App for using Docker-Compose on TrueNAS SCALE
home: https://truecharts.org/charts/stable/docker-compose
icon: https://truecharts.org/img/hotlink-ok/chart-icons/docker-compose.png
keywords:
  - docker-compose
  - docker
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: truenas-github@mds.name
    name: MDS
    url: https://truecharts.org
name: docker-compose
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/docker-compose
type: application
version: 1.0.2

